
name: within
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true

  image_path_android: "assets/icons/within_app_icon.png"
  image_path_ios: "assets/icons/within_app_icon.png"

  adaptive_icon_background: "#F5F3FD"
  adaptive_icon_foreground: "assets/icons/within_android_foreground.png"
  adaptive_icon_foreground_inset: 0

  remove_alpha_ios: true
  min_sdk_android: 21


flutter_native_splash:
  color: "#F5F3FD"

  android: true
  ios: false
  web: false

  image_android: "assets/icons/within_android_splash.png"

  android_12:
    color: "#F5F3FD"
    image: "assets/icons/within_android_splash.png"
